#!/usr/bin/env python3

import csv
import requests
import sys
import xml.etree.ElementTree as ET


def classify_response_code(xml):
    return int(xml.find(
        './/{http://classify.oclc.org}response').attrib['code'])


def get_by_oclc(oclc):
    r = requests.get(
        "http://classify.oclc.org/classify2/Classify?oclc={}".format(oclc))
    r.raise_for_status()
    root = ET.fromstring(r.text)
    return extract_classify(root)


def get_by_lccn(lccn):
    r = requests.get(
        "http://classify.oclc.org/classify2/Classify?lccn={}".format(lccn))
    r.raise_for_status()
    root = ET.fromstring(r.text)
    return extract_classify(root)


def extract_classify(xml):
    rc = classify_response_code(xml) 
    if rc == 2:
        work = xml.find(".//{http://classify.oclc.org}work")
        book = ", ".join(
            [g for g in
             [work.attrib.get(f) for f in ["author", "title"]]
             if g is not None])
        return {"oclc-book": book,
                "oclc-owi": work.attrib["owi"],
                "oclc-main-id": work.text,
                "oclc-type": work.attrib["format"],
                "oclc-editions": work.attrib["editions"],
                "oclc-holdings": work.attrib["holdings"],
                "oclc-eholdings": work.attrib["eholdings"]}

    if rc == 102:
        return {}

    

    raise Exception(
        "Classify response code {}".format(classify_response_code(xml)))

reader = csv.DictReader(sys.stdin, delimiter="\t")
writer = csv.DictWriter(sys.stdout, delimiter="\t",
                        fieldnames=['ia_id', 'cce_id', 'match_quality',
                                    'ia-book', 'ia-date', 'ia-openlibrary',
                                    'ia-lccn', 'ia-oclc', 'oclc-book',
                                    'oclc-owi', 'oclc-main-id', 'oclc-type',
                                    'oclc-editions', 'oclc-holdings',
                                    'oclc-eholdings'])
writer.writeheader()

for line in reader:
    if line["ia-oclc"]:
        cfy = get_by_oclc(line["ia-oclc"])
    elif line["ia-lccn"]:
        cfy = get_by_oclc(line["ia-lccn"])
    else:
        cfy = {}
    
    line["oclc-book"] = cfy.get("oclc-book")
    line["oclc-owi"] = cfy.get("oclc-owi")
    line["oclc-main-id"] = cfy.get("oclc-main-id")
    line["oclc-type"] = cfy.get("oclc-type")
    line["oclc-editions"] = cfy.get("oclc-editions")
    line["oclc-holdings"] = cfy.get("oclc-holdings")
    line["oclc-eholdings"] = cfy.get("oclc-eholdings")
    writer.writerow(line)
